apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-latest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity-app
  template:
    metadata:
      labels:
        app: udacity-app
    spec:
      containers:
      - name: udacity-app-container
        image: 947772818907.dkr.ecr.us-east-1.amazonaws.com/udacity-new:latest